// <auto-generated />
using E_RaporWebApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace E_RaporWebApplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220203111258_tb_guru")]
    partial class tb_guru
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("E_RaporWebApplication.Models.DbAchievements", b =>
                {
                    b.Property<string>("Nomor")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Deskripsi")
                        .HasColumnType("text");

                    b.Property<string>("Jenis_Prestasi")
                        .HasColumnType("text");

                    b.Property<string>("NIS")
                        .HasColumnType("text");

                    b.Property<string>("Nama")
                        .HasColumnType("text");

                    b.HasKey("Nomor");

                    b.ToTable("Tb_Prestasi");
                });

            modelBuilder.Entity("E_RaporWebApplication.Models.DbAttitudeCompetence", b =>
                {
                    b.Property<string>("Nomor")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Deskripsi_Sikap")
                        .HasColumnType("text");

                    b.Property<string>("NIS")
                        .HasColumnType("text");

                    b.Property<string>("Nama")
                        .HasColumnType("text");

                    b.HasKey("Nomor");

                    b.ToTable("DbAttitudeCompetence");
                });

            modelBuilder.Entity("E_RaporWebApplication.Models.DbExtracurricular", b =>
                {
                    b.Property<string>("Nomor")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Ekstrakurikuler")
                        .HasColumnType("text");

                    b.Property<string>("Grade")
                        .HasColumnType("text");

                    b.Property<string>("NIS")
                        .HasColumnType("text");

                    b.Property<string>("Nama")
                        .HasColumnType("text");

                    b.HasKey("Nomor");

                    b.ToTable("Tb_Ekstrakurikuler");
                });

            modelBuilder.Entity("E_RaporWebApplication.Models.DbStudentData", b =>
                {
                    b.Property<string>("NIS")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Alamat")
                        .HasColumnType("text");

                    b.Property<string>("Jenis_Kelamin")
                        .HasColumnType("text");

                    b.Property<string>("NISN")
                        .HasColumnType("text");

                    b.Property<string>("Nama")
                        .HasColumnType("text");

                    b.HasKey("NIS");

                    b.ToTable("Tb_Siswa");
                });

            modelBuilder.Entity("E_RaporWebApplication.Models.DbSubjects", b =>
                {
                    b.Property<string>("Nomor")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Bahasa_Indonesia")
                        .HasColumnType("text");

                    b.Property<string>("IPA")
                        .HasColumnType("text");

                    b.Property<string>("IPS")
                        .HasColumnType("text");

                    b.Property<string>("Matematika")
                        .HasColumnType("text");

                    b.Property<string>("NIS")
                        .HasColumnType("text");

                    b.Property<string>("Nama")
                        .HasColumnType("text");

                    b.Property<string>("PJOK")
                        .HasColumnType("text");

                    b.Property<string>("PPKN")
                        .HasColumnType("text");

                    b.Property<string>("Pendidikan_Agama")
                        .HasColumnType("text");

                    b.HasKey("Nomor");

                    b.ToTable("Tb_Mata_Pelajaran");
                });

            modelBuilder.Entity("E_RaporWebApplication.Models.DbTeacherData", b =>
                {
                    b.Property<string>("Nomor")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Mata_Pelajaran")
                        .HasColumnType("text");

                    b.Property<string>("NUPTK")
                        .HasColumnType("text");

                    b.Property<string>("Nama")
                        .HasColumnType("text");

                    b.HasKey("Nomor");

                    b.ToTable("Tb_Guru");
                });
#pragma warning restore 612, 618
        }
    }
}
