// <auto-generated />
using E_RaporWebApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace E_RaporWebApplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220201070732_Tb_Guru")]
    partial class Tb_Guru
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("E_RaporWebApplication.Models.TeacherData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Mata_Pelajaran")
                        .HasColumnType("text");

                    b.Property<string>("NUPTK")
                        .HasColumnType("text");

                    b.Property<string>("Nama")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Tb_Guru");
                });
#pragma warning restore 612, 618
        }
    }
}
